name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
    tags:
      - "*"

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            DOCKER_TAG="${GITHUB_REF:10}"
          elif [[ $GITHUB_REF == refs/heads/development ]]; then
            DOCKER_TAG="dev"
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF:11}"
          fi
          echo ::set-output name=tag::${DOCKER_TAG}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      # https://github.com/docker/build-push-action
      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: whatdaybob/sonarr_youtubedl:${{ steps.tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max